In [1]:
import numpy as np
import pandas as pd

In [2]:
bike_data=pd.read_csv('daily-bike-share.csv')

In [3]:
bike_data.head()

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011       1   0     1        0        6           0   
1        2  1/2/2011       1   0     1        0        0           0   
2        3  1/3/2011       1   0     1        0        1           1   
3        4  1/4/2011       1   0     1        0        2           1   
4        5  1/5/2011       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331  
1           2  0.363478  0.353739  0.696087   0.248539      131  
2           1  0.196364  0.189405  0.437273   0.248309      120  
3           1  0.200000  0.212122  0.590435   0.160296      108  
4           1  0.226957  0.229270  0.436957   0.186900       82

In [4]:
bike_data.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
rentals       0
dtype: int64

In [5]:
# #Encoding: We convert our categorical into the numerical label.
# bike_data['season']=bike_data['season'].map({1:'Spring', 2:'Summer', 3:'Fall', 4:'Winter'})
bike_data['season']=bike_data['season'].map({'Spring':1,'Summer':2, 'Fall':3, 'Winter':4})

In [6]:
bike_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     731 non-null    int64  
 1   dteday      731 non-null    object 
 2   season      0 non-null      float64
 3   yr          731 non-null    int64  
 4   mnth        731 non-null    int64  
 5   holiday     731 non-null    int64  
 6   weekday     731 non-null    int64  
 7   workingday  731 non-null    int64  
 8   weathersit  731 non-null    int64  
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  rentals     731 non-null    int64  
dtypes: float64(5), int64(8), object(1)
memory usage: 80.1+ KB


In [7]:
bike_data.head()

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011     NaN   0     1        0        6           0   
1        2  1/2/2011     NaN   0     1        0        0           0   
2        3  1/3/2011     NaN   0     1        0        1           1   
3        4  1/4/2011     NaN   0     1        0        2           1   
4        5  1/5/2011     NaN   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331  
1           2  0.363478  0.353739  0.696087   0.248539      131  
2           1  0.196364  0.189405  0.437273   0.248309      120  
3           1  0.200000  0.212122  0.590435   0.160296      108  
4           1  0.226957  0.229270  0.436957   0.186900       82

In [8]:
type(bike_data)

pandas.core.frame.DataFrame

In [11]:
bike_data[features].values

array([[      nan,  1.      ,  0.      , ...,  0.363625,  0.805833,
         0.160446],
       [      nan,  1.      ,  0.      , ...,  0.353739,  0.696087,
         0.248539],
       [      nan,  1.      ,  0.      , ...,  0.189405,  0.437273,
         0.248309],
       ...,
       [      nan, 12.      ,  0.      , ...,  0.2424  ,  0.752917,
         0.124383],
       [      nan, 12.      ,  0.      , ...,  0.2317  ,  0.483333,
         0.350754],
       [      nan, 12.      ,  0.      , ...,  0.223487,  0.5775  ,
         0.154846]])

In [10]:
# Separate features and labels
features=['season','mnth', 'holiday','weekday','workingday','weathersit','temp', 'atemp', 'hum', 'windspeed']
X = bike_data[features].values


y = bike_data['rentals'].values


print('Features:',X[:10], '\nLabels:', y[:10], sep='\n')

Features:
[[      nan 1.        0.        6.        0.        2.        0.344167
  0.363625  0.805833  0.160446 ]
 [      nan 1.        0.        0.        0.        2.        0.363478
  0.353739  0.696087  0.248539 ]
 [      nan 1.        0.        1.        1.        1.        0.196364
  0.189405  0.437273  0.248309 ]
 [      nan 1.        0.        2.        1.        1.        0.2
  0.212122  0.590435  0.160296 ]
 [      nan 1.        0.        3.        1.        1.        0.226957
  0.22927   0.436957  0.1869   ]
 [      nan 1.        0.        4.        1.        1.        0.204348
  0.233209  0.518261  0.0895652]
 [      nan 1.        0.        5.        1.        2.        0.196522
  0.208839  0.498696  0.168726 ]
 [      nan 1.        0.        6.        0.        2.        0.165
  0.162254  0.535833  0.266804 ]
 [      nan 1.        0.        0.        0.        1.        0.138333
  0.116175  0.434167  0.36195  ]
 [      nan 1.        0.        1.        1.        1.        

In [12]:
type(X)

numpy.ndarray

In [13]:
type(y)

numpy.ndarray

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# Split data 70%-30% into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


# '''
# 1: training data feature
# 2: testing data feature
# 3: training data target
# 4: testing data target
# '''

In [16]:
y_test

array([ 872,  670, 2015,  486,   65,  982,  599,  208,  118,  178,  601,
        181,  736,  724,  750, 1448,  247,  441,  728,  477,  255,   38,
         69, 1070, 1603,  305,  907,  253, 1633, 1001, 2207,   57, 2204,
        935, 1319, 1031, 1008,  320,  195,  979,  188, 1483,  640,  775,
        359,  892,  107,  618, 2557, 1246,  706,  145, 2589,  998,  606,
        545,  692, 3160,  131,  909, 1549,  123,  114,  324, 2657,  470,
        848, 2247,   74,  290,  539,  686, 1965, 1180,  795, 1088, 1263,
        244,  491,  801,  753, 1524,  662,  784,   92,  471,  126,  330,
        139,  217, 1710, 2135,  922,  254,  745,  227,  203,  198,  439,
         81,  855,  435,   86,  955, 2252,  738,    9, 1070, 1807,  891,
        243, 2132, 1014,  163,  408,  120,  699,  466,    9,   72, 2182,
        699,  153,  688, 1118,  949, 1405,  560,  529,  413,  684,  327,
        354,  432,  875,  275,  989,  186,  867,  260, 1029,  678,  150,
        377, 1582, 2496,   73, 1017,  735, 1514, 11

In [17]:
print ('Training Set: %d rows\nTest Set: %d rows' % (X_train.shape[0], X_test.shape[0]))

Training Set: 511 rows
Test Set: 220 rows


In [18]:
# Train the model
from sklearn.linear_model import LinearRegression

In [21]:

model = LinearRegression().fit(X_train_imputed, y_train)

print(model)

LinearRegression()


In [25]:
# Assuming you used the same imputer that was fitted on X_train
X_test_imputed = imputer.transform(X_test)

# Now make predictions
predictions = model.predict(X_test_imputed)

# Display the predicted and actual labels
print('Predicted labels: ', np.round(predictions, 0)[:10])
print('Actual labels   : ', y_test[:10])


Predicted labels:  [1354. 1473. 1552.  484.  141.  685. 1163.  316.  612.  296.]
Actual labels   :  [ 872  670 2015  486   65  982  599  208  118  178]


C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:598: UserWarning: Skipping features without any observed values: [0]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


In [26]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

r2 = r2_score(y_test, predictions)
print("R2:", r2*100)

MSE: 149338.58628213912
RMSE: 386.44350982017943
R2: 64.82395246496321


In [27]:
model

LinearRegression()

In [46]:
pwd

'C:\\Users\\hp\\ML file'

In [47]:
import joblib

In [48]:

joblib.dump(model,"bike_model.pkl") #writing step

['bike_model.pkl']

In [49]:
# Load the model from the file
loaded_model = joblib.load("bike_model.pkl")

In [32]:
X_train[0]

array([      nan, 10.      ,  0.      ,  2.      ,  1.      ,  2.      ,
        0.318182,  0.309909,  0.825455,  0.213009])

In [33]:
bike_data.head(1)

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011     NaN   0     1        0        6           0   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331

In [34]:
season=float(input("Enter the season"))
month=float(input("Enter the month"))
holiday=float(input("Enter the holiday"))
weekday=float(input("Enter the weekday"))
workingday=float(input("Enter the workingday"))
weathersit=float(input("Enter the weathersit"))
temp=float(input("Enter the temp"))
atemp=float(input("Enter the atemp"))
hum=float(input("Enter the hum"))
windspeed=float(input("Enter the windspeed"))

Enter the season 1
Enter the month 1
Enter the holiday 1
Enter the weekday 2
Enter the workingday 1
Enter the weathersit 34
Enter the temp 34
Enter the atemp 1
Enter the hum 2
Enter the windspeed 25


In [36]:
X_new = np.array([[season, month, holiday, weekday, workingday, weathersit, temp, atemp, hum]])


In [37]:
result = loaded_model.predict(X_new)
print('Prediction: {:.0f} rentals'.format(np.round(result[0])))


Prediction: 70269 rentals


In [38]:
X_new

array([[ 1.,  1.,  1.,  2.,  1., 34., 34.,  1.,  2.]])

In [39]:
# Create a numpy array containing a new observation (for example tomorrow's seasonal and weather forecast information)
X_new = np.array([[1,6,1,0,1,2,0.326957,0.02927,0.686957,0.1869]]).astype('float64')
print ('New sample: {}'.format(list(X_new[0])))

New sample: [np.float64(1.0), np.float64(6.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(0.326957), np.float64(0.02927), np.float64(0.686957), np.float64(0.1869)]


In [41]:
result[0]

np.float64(70268.63994387093)

In [42]:
# An array of features based on five-day weather forecast
X_new = np.array([[0,1,1,0,0,1,0.344167,0.363625,0.805833,0.16044],
                  [0,1,0,1,0,1,0.363478,0.353739,0.696087,0.248539],
                  [0,1,0,2,0,1,0.196364,0.189405,0.437273,0.248309],
                  [0,1,0,3,0,1,0.2,0.212122,0.590435,0.160296],
                  [0,1,0,4,0,1,0.226957,0.22927,0.436957,0.1869]])

In [43]:
X_new

array([[0.      , 1.      , 1.      , 0.      , 0.      , 1.      ,
        0.344167, 0.363625, 0.805833, 0.16044 ],
       [0.      , 1.      , 0.      , 1.      , 0.      , 1.      ,
        0.363478, 0.353739, 0.696087, 0.248539],
       [0.      , 1.      , 0.      , 2.      , 0.      , 1.      ,
        0.196364, 0.189405, 0.437273, 0.248309],
       [0.      , 1.      , 0.      , 3.      , 0.      , 1.      ,
        0.2     , 0.212122, 0.590435, 0.160296],
       [0.      , 1.      , 0.      , 4.      , 0.      , 1.      ,
        0.226957, 0.22927 , 0.436957, 0.1869  ]])

In [ ]:
results

In [ ]:
print('5-day rental predictions:')
for prediction in results:
    print(np.round(prediction))